# Generated by Django 4.2.26 on 2025-11-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='device',
        ),
        migrations.DeleteModel(
            name='OTPDevice',
        ),
        migrations.DeleteModel(
            name='OTPToken',
        ),
    ]
