# Generated by Django 4.2.26 on 2025-12-12 14:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('core', '0002_aboutuspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('error_code', models.CharField(choices=[('401', '401 - Unauthorized'), ('403', '403 - Forbidden'), ('404', '404 - Not Found'), ('500', '500 - Internal Server Error'), ('502', '502 - Bad Gateway'), ('503', '503 - Service Unavailable')], help_text='HTTP error code this page represents', max_length=3, unique=True)),
                ('error_title', models.CharField(default='Oops! Something went wrong', max_length=200)),
                ('error_message', wagtail.fields.RichTextField(blank=True, help_text='Custom error message')),
                ('show_home_button', models.BooleanField(default=True)),
                ('show_back_button', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Error Page',
                'verbose_name_plural': 'Error Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
