# Generated by Django 4.2.26 on 2025-11-28 08:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Welcome to Brickaria', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('content', wagtail.fields.StreamField([('hero', 5), ('features', 10), ('featured_games', 14), ('stats', 18), ('rich_text', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 3), ('cta_link', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Bootstrap icon class', 'max_length': 50}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('icon', 6), ('title', 7), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'template': 'blocks/features_section.html'}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 30}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 8), ('image', 2), ('game_link', 4), ('tags', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'template': 'blocks/games_section.html'}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 17: ('wagtail.blocks.StructBlock', [[('stat_value', 15), ('stat_label', 16), ('icon', 3)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'template': 'blocks/stats_section.html'}), 19: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
