# Generated by Django 4.2.26 on 2025-11-28 08:52

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store_type', models.CharField(choices=[('playstore', 'Google Play Store'), ('appstore', 'Apple App Store'), ('steam', 'Steam')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='CSS icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'App Store Link',
                'verbose_name_plural': 'App Store Links',
            },
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_subtitle',
            new_name='newsletter_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='achievements',
            field=wagtail.fields.StreamField([('achievement', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Bootstrap icon class', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='coming_soon_games',
            field=wagtail.fields.StreamField([('game', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.DateBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('release_date', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_metrics',
            field=wagtail.fields.StreamField([('metric', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1), ('icon', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_games',
            field=wagtail.fields.StreamField([('game', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.DateBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('game_link', 3), ('release_date', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 3), ('cta_link', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(default='Stay Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_content',
            field=wagtail.fields.StreamField([('vision', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}),
        ),
    ]
