# Generated by Django 4.2.26 on 2025-11-28 08:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
                ('team_content', wagtail.fields.StreamField([('team_member', 5), ('rich_text', 6)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['teams.TeamMember'], 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('member', 0), ('name', 1), ('role', 2), ('bio', 3), ('avatar', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Teams Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('artist', 'Artist'), ('manager', 'Manager'), ('qa', 'QA Tester'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
